// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rofrvimzrodrgybxegfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZnJ2aW16cm9kcmd5YnhlZ2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzI2MTQsImV4cCI6MjA3NDAwODYxNH0.DscQHwdw1wVSKkUcGyFZKEvM6mOyuZ2Mja3eUZhbbPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});